name: Testing

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    name: Testing
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j
        env:
          NEO4J_AUTH: neo4j/${{ secrets.NEO4J_PASSWORD }}
        ports:
          - 7687:7687

    steps:
      - name: Install dependencies
        id: install_dependencies
        run: pip3 install -r packages.txt

      - name: Run tests
        id: run_tests
        run: ./scripts/ci/run_tests.sh